"""
Read Data from file called "input.txt", which should be generated by GUI.


The format of the GUI's output should be
name, parameter, parameter, parameter,.....
for example:
------------------------------------------------------------------------------
tetrahedron,0,-0.5,1.5,0.8,-0.5,1.5,0.25,-0.5,0.8,0.25,0.4,0.75,1,0.3,0.25
cube,1,0.5,1.2,0.6,30,0,30,0.4,0.81,0.6
cylinder,-0.75,0.25,1,0.5,0.4,-30,0,30,0.5,0.223,0.5
cube,-2.75,0.1,3.5,0.6,0,0,0,1,0.572,0.184
plane,0,-0.5,0,0,1,0
sphere,-2.75,0.1,3.5,0.6,0,0,0,1,0.572,0.184
------------------------------------------------------------------------------

There are different requirement for different shapes
For tetrahedron:
tetrahedron,position,color
For cube:
cube,position,length,rotation_angle,color
For cylinder:
cylinder,position,height,radius,rotation_angle,color
For sphere:
sphere,position,radius,color
For plane:
plane,position,normal

"""

file = open('input.txt', 'r')
totalLines = file.readlines()
lists = []
for line in totalLines:
    lists.append(line.split(','))


def addTetrahedron():
    print("add tetrahedron")

def addCube():
    print("add cube")

def addCylinder():
    print("add cylinder")

def addSphere():
    print("add sphere")

def addPlane():
    print("add plane")



def make_all_float(lst):
    return [float(itr) for itr in lst]



sence = []

for i in range(len(lists)):
    if lists[i][0] == 'tetrahedron':
        addTetrahedron()
        tmp= make_all_float(lists[i][1:])
        position = tuple((tmp[0:3],)) + (tmp[3:6],) + (tmp[6:9],) + (tmp[9:12],)
        color = tmp[12:]
        #sence.append(add_tetrahedron(position, color))

    elif lists[i][0] == 'cube':
        addCube()
        tmp = make_all_float(lists[i][1:])
        # print(tmp)
        position = tmp[0:3]
        # print(position)
        length = tmp[3]
        # print(length)
        rotation_angle = tmp[4:7]
        # print(rotation_angle)
        color = tmp[7:]
        # print(color)

        sence.append(add_cube(position, length, rotation_angle, color))

    elif lists[i][0] == 'cylinder':
        addCylinder()

        tmp = make_all_float(lists[i][1:])
        position = tmp[0:3]
        # print(position)
        height = tmp[3]
        # print(height)
        radius = tmp[4]
        # print(radius)
        rotation_angle = tmp[5:8]
        # print(rotation_angle)
        color = tmp[8:]
        # print(color)
        sence.append(add_cylinder(position, height, radius, rotation_angle, color))

    elif lists[i][0] == 'sphere':
        addSphere()

        tmp = make_all_float(lists[i][1:])
        position = tmp[0:3]
        radius = tmp[3]
        color = tmp[4:]
        sence.append(add_sphere(position, radius, color))

    elif lists[i][0] == 'plane':
        addPlane()

        tmp = make_all_float(lists[i][1:])
        position = tmp[0:3]
        normal = tmp[3:]
        sence.append(add_plane(position, normal))
